name: Test 

on:
  push: 
    branches:
      - $default-branch 
  pull_request: 

jobs:
  getNodeVersion:
    uses: yalochat/.github/.github/workflows/get_node_version.yml@main

  unitTest:
    runs-on: ubuntu-latest 
    needs: getNodeVersion 
    steps: 
      - uses: actions/checkout@v3 
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }} 
        uses: actions/setup-node@v2 
        with:
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}' 
      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '.yarn/cache'
          key: ${{ runner.os }}-yarn-${{ needs.getNodeVersion.outputs.node_version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn 
      - name: Run Tests
        run: yarn test 
      - name: Send coverage to codecov
        uses: codecov/codecov-action@v2
        with: 
          token: ${{ secrets.CODECOV_TOKEN }} # you will need the CODECOV_TOKEN that can be found on https://app.codecov.io/gh/yalochat/${REPOSITORY_NAME}
          flags: unittests 
