name: Test 

on:
  push: 
    branches:
      - $default-branch 
    pull_request: 

jobs:
  getNodeVersion:
    uses: yalochat/.github/.github/workflows/get_node_version.yml@main

  unitTest:
    runs-on: ubuntu-latest 
    needs: getNodeVersion 
    steps: 
      - uses: actions/checkout@v3 
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }} 
        uses: actions/setup-node@v2 
        with:
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'
          cache: 'npm'
            - name: NPM credentials
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{secrets.NPM_TOKEN}}"
      - name: Install dependencies
        run: npm i
      - name: Run Tests
        run: npm run test 
      - name: Send coverage to codecov
        uses: codecov/codecov-action@v2
        with: 
          token: ${{ secrets.CODECOV_TOKEN }} # you will need the CODECOV_TOKEN that can be found on https://app.codecov.io/gh/yalochat/${REPOSITORY_NAME}
          flags: unittests 
