name: Lint 

on:
  push:
    branches:
      - $default-branch 
  pull_request:

jobs:
  getNodeVersion:
    uses: yalochat/.github/.github/workflows/get_node_version.yml@main

  lint:
    runs-on: ubuntu-latest 
    needs: getNodeVersion
    steps: 
      - uses: actions/checkout@v3 
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }} 
        uses: actions/setup-node@v2 
        with: 
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Run lint
        run: npm run lint 
