# File: .github/workflows/repo-sync.yml
name:
  Sync this repo with remote repo into feature branch
  
on:
  schedule:
  - cron:  "0 0 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git LFS
      run: |
        git lfs install
    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        lfs: true
        persist-credentials: false
    - name: Add remote repo
      run: |
        git remote add source https://${{ secrets.REMOTE_PAT }}@github.com/{your_repo_org_and_reponame}
    - name: Fetch from remote repo
      run: |
        git fetch source main
    - name: Checkout to destination branch
      run: |
        git checkout -b remote_main
    - name: Merge changes from remote repo
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action Bot"
        git merge source/main --allow-unrelated-histories
    - name: Set up Git credentials
      run: |
        git config credential.helper '!f() { echo username=$GH_TOKEN; echo password=$GH_TOKEN; }; f'
    - name: Check if remote_main branch exists
      run: |
        git ls-remote --exit-code --heads origin remote_main || git push origin remote_main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull changes from remote_main branch
      run: |
        git pull --ff-only origin remote_main || git merge --no-ff origin/remote_main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push changes to this repo
      run: |
        git push origin remote_main
      env:
        GIT_COMMITTER_NAME: 'github-actions[bot]'
        GIT_COMMITTER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
        GIT_AUTHOR_NAME: 'github-actions[bot]'
        GIT_AUTHOR_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
