name: Lint # lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  getNodeVersion:
    uses: yalochat/.github/.github/workflows/get_node_version.yml@main

  lint:
    env:
      NPM_TOKEN: ""
    runs-on: ubuntu-latest 
    needs: getNodeVersion
    steps: 
      - uses: actions/checkout@v3 
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }} 
        uses: actions/setup-node@v2 
        with: 
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'
          cache: 'npm'
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{secrets.NPM_TOKEN}}"
      - run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc
      - name: Install dependencies
        run: npm ci
      # NO NPM RUN CHECK in the original BB repo (master or develop branches)
        
