name: UploadMicroFEToBucket

on:
  workflow_call:
    inputs:
      project_name:
        description: "Project name for cdn path"
        type: string
        required: true
      artifact_key:
        description: 'Key name for artifact uploaded in prior steps, by default we will look for "dist" key'
        type: string
        required: true
      artifact_location:
        description: "Key name for artifact uploaded in prior steps, by default we will look for 'dist' key"
        type: string
        required: true
      environment:
        description: "Environment name to be use the correct variables on jobs"
        type: string
        required: false
        default: staging

    secrets:
      GOOGLE_CREDENTIALS:
        description: "Google json credentials"
        required: true
      GOOGLE_BUCKET:
        description: "Google bucket name"
        required: true

jobs:
  upload-to-bucket:
    name: Upload dist to Bucket
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    environment: ${{inputs.environment}}

    steps:
      - name: Create forlder
        run: mkdir -p ${{inputs.project_name}}/${{inputs.artifact_location}}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact_key}}
          path: ${{inputs.project_name}}/${{inputs.artifact_location}}

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS}}"

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: ${{inputs.project_name}}/${{inputs.artifact_location}}
          destination: ${{secrets.GOOGLE_BUCKET}}
          gzip: true
